### ISSUE TITLE
No Clear threat button,

### ISSUE THREAD

**Issue by Gatorzgaming** [ccuser44/Titan-Protection#2]
Context it quarantined safe stuff and there was no button to un quarenteen something

**Comment by ccuser44** [comment]
Yes. I am currently aware of this issue. It stems from the fact that the plugin currently doesn't have any UI. I am currenly in the making of the UI. I have arranged a prototype of the scanning UI which looks good. I currently don't have much time to work on Ti-Protection but in the near future the updated plugin will be released along with functioning scanning and scan results UI.

**Comment by ccuser44** [comment]
The current way to unquarantine them is to select the stuff you want to unquarantine. (The objects under the quarantine folder which start with "Malicious Object-") and run this code in the commandbar
`
for _, v in ipairs(game:GetService("Selection"):Get()) do if v:IsA("Folder") and string.sub(v.Name, 1, 17) == "Malicious Object-" then local Obj = v:FindFirstChild("OriginalObject") and v:FindFirstChild("OriginalObject"):GetChildren()[1];if Obj then if v:FindFirstChild("Detection") and Obj:IsA("BaseScript") then Obj.Disabled = false;end;Obj.Parent = v:FindFirstChild("OriginalParent") and v:FindFirstChild("OriginalParent").Value;end;v:Destroy();end;end
`

**Comment by ccuser44** [comment]
Project discontinued a long time ago
